### ISSUE TITLE
release 离线包在哪里？

### ISSUE THREAD

**Issue by laiweiwei** [WeBankFinTech/Dockin-Installer#6]
release 离线包在哪里？

**Comment by gzchen008** [comment]
The offline installation package is located at the bottom of the release page, Assets.
离线安装包位于release页的最底下，Assets那里。
https://github.com/WeBankFinTech/Dockin-Installer/releases
![image](https://user-images.githubusercontent.com/12092692/105288909-f543b300-5bf2-11eb-9f0a-b101fcc89127.png)

**Comment by laiweiwei** [comment]
可以在gitee也放一份吗，这里下载很慢 : )

**Comment by laiweiwei** [comment]
在公司电脑试了很多次，无法下载release的离线包，建议在gitee也放一份

**Comment by laiweiwei** [comment]
在公司电脑试了很多次，无法下载release的离线包，建议在gitee也放一份

**Comment by gzchen008** [comment]
https://osp-1257653870.cos.ap-guangzhou.myqcloud.com/Dockin/dockin-etcd_0.1.1_dist.tar.gz
https://osp-1257653870.cos.ap-guangzhou.myqcloud.com/Dockin/dockin-docker_0.1.1_dist.tar.gz
https://osp-1257653870.cos.ap-guangzhou.myqcloud.com/Dockin/dockin-worker_0.1.1_dist.tar.gz
https://osp-1257653870.cos.ap-guangzhou.myqcloud.com/Dockin/dockin-master_0.1.1_dist.tar.gz
